// Acceptance Test
// Traces to: L2-031, L2-034
// Description: InventoryRenderer emits a title, a Summary with
// total/exported/internal counts and a per-category count table, then one section
// per non-empty category (in a fixed order) with Name/Kind/Exported/File/Description
// columns. Output is deterministic, pipe-safe, and explicit about empty projects.

using SurfaceQ.Core;
using Xunit;

namespace SurfaceQ.Core.Tests;

public class InventoryRendererTests
{
    [Fact]
    public void Renders_summary_and_per_category_sections()
    {
        var inventory = new ProjectInventory("web", "application", new[]
        {
            Item("ZComponent", "class", "Component", true, "src/app/z.component.ts", "Last."),
            Item("AppComponent", "class", "Component", true, "src/app/app.component.ts", "Root component."),
            Item("UserService", "class", "Service", true, "src/app/user.service.ts", ""),
            Item("Shape", "interface", "Interface", false, "src/app/shape.ts", ""),
            Item("Pricing", "type", "Type Alias", true, "src/app/pricing.ts", "a | b state."),
        });

        var md = new InventoryRenderer().Render(inventory);

        Assert.Contains("# web — Inventory", md);
        Assert.DoesNotContain("Generated by SurfaceQ", md);
        Assert.DoesNotContain("regenerate", md, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("_Type: application_", md);

        Assert.Contains("## Summary", md);
        Assert.Contains("5 objects (4 exported, 1 internal).", md);
        Assert.Contains("| Components | 2 |", md);
        Assert.Contains("| Services | 1 |", md);
        Assert.Contains("| Interfaces | 1 |", md);
        Assert.Contains("| Type Aliases | 1 |", md);

        Assert.Contains("## Components", md);
        Assert.Contains("| `AppComponent` | `class` | yes | `src/app/app.component.ts` | Root component. |", md);
        Assert.Contains("| `Shape` | `interface` | no | `src/app/shape.ts` | – |", md);

        // Pipe inside a description is escaped so it cannot break the table cell.
        Assert.Contains("| `Pricing` | `type` | yes | `src/app/pricing.ts` | a \\| b state. |", md);

        // Fixed category order: Components before Services before Interfaces.
        Assert.True(md.IndexOf("## Components") < md.IndexOf("## Services"));
        Assert.True(md.IndexOf("## Services") < md.IndexOf("## Interfaces"));
        // Rows sorted by name within a section.
        Assert.True(md.IndexOf("`AppComponent`") < md.IndexOf("`ZComponent`"));
    }

    [Fact]
    public void Is_deterministic_regardless_of_input_order()
    {
        // B and C share the Classes section, so a stable sort — not input order —
        // must drive the output. Rendering two different orderings proves it.
        var a = Item("A", "interface", "Interface", true, "src/a.ts", "");
        var b = Item("B", "class", "Class", true, "src/b.ts", "");
        var c = Item("C", "class", "Class", false, "src/c.ts", "");
        var forward = new ProjectInventory("lib", "library", new[] { a, b, c });
        var shuffled = new ProjectInventory("lib", "library", new[] { c, a, b });

        var renderer = new InventoryRenderer();
        Assert.Equal(renderer.Render(forward), renderer.Render(shuffled));
    }

    [Fact]
    public void Sorts_same_named_items_by_file()
    {
        var inventory = new ProjectInventory("lib", "library", new[]
        {
            Item("Helper", "function", "Function", true, "src/b.ts", ""),
            Item("Helper", "function", "Function", true, "src/a.ts", ""),
        });

        var md = new InventoryRenderer().Render(inventory);

        Assert.True(md.IndexOf("`src/a.ts`") < md.IndexOf("`src/b.ts`"));
    }

    [Fact]
    public void Ends_with_exactly_one_trailing_newline()
    {
        var inventory = new ProjectInventory("lib", "library", new[]
        {
            Item("A", "class", "Class", true, "src/a.ts", ""),
        });

        var md = new InventoryRenderer().Render(inventory);

        Assert.EndsWith("|\n", md);
        Assert.False(md.EndsWith("\n\n", StringComparison.Ordinal));
    }

    [Fact]
    public void Renders_explicit_line_for_empty_project()
    {
        var md = new InventoryRenderer().Render(new ProjectInventory("empty", "library", Array.Empty<InventoryItem>()));

        Assert.Contains("# empty — Inventory", md);
        Assert.Contains("_No developer-authored objects found._", md);
        Assert.DoesNotContain("## Summary", md);
    }

    private static InventoryItem Item(string name, string kind, string role, bool exported, string file, string doc) =>
        new(name, kind, role, exported, file, doc, false, "");
}
