using System.Text;

namespace SurfaceQ.Core;

// Renders a FicdProject (authored metadata) plus a LibraryApi (extracted symbols)
// into a multi-file FICD document set. Each section becomes one output file at its
// authored relative path; a README index is generated from the manifest. Every
// document starts with an identity block; service/function/data-object templates
// fill tables from the resolved symbols. Output is deterministic, pipe-safe,
// LF-terminated. Symbol/group order is preserved; the first declaration wins on a
// name collision. See docs/specs/ficd-schema.md.

public sealed class FicdRenderer
{
    public IReadOnlyList<FicdOutputFile> Render(FicdProject project, LibraryApi api)
    {
        var symbols = BuildSymbolTable(api);
        var files = new List<FicdOutputFile>
        {
            new("README.md", RenderReadme(project)),
        };
        foreach (var section in project.Sections)
        {
            files.Add(new FicdOutputFile(
                section.RelativePath, RenderSection(section, project.Manifest, symbols)));
        }
        return files;
    }

    private static Dictionary<string, ApiDeclaration> BuildSymbolTable(LibraryApi api)
    {
        var map = new Dictionary<string, ApiDeclaration>(StringComparer.Ordinal);
        foreach (var d in api.Declarations)
        {
            if (!map.ContainsKey(d.Name))
            {
                map[d.Name] = d;
            }
        }
        return map;
    }

    // --- README -----------------------------------------------------------

    private static string RenderReadme(FicdProject project)
    {
        var sb = new StringBuilder();
        var manifest = project.Manifest;
        var title = !string.IsNullOrEmpty(manifest.DocumentTitle)
            ? manifest.DocumentTitle
            : project.LibraryName + " — FICD";
        AppendIdentity(sb, title, manifest, includeSection: false);
        sb.Append("This Functional Interface Control Document is generated by SurfaceQ from the ")
          .Append("library's `ficd/` metadata folder and its TypeScript sources.\n\n");
        sb.Append("---\n\n");
        AppendDocumentSet(sb, project);
        return Trim(sb);
    }

    private static void AppendDocumentSet(StringBuilder sb, FicdProject project)
    {
        var ordered = OrderedDocuments(project);
        if (ordered.Count == 0)
        {
            sb.Append("_This FICD has no section documents._\n\n");
            return;
        }
        sb.Append("## Document Set\n\n");
        sb.Append("| # | Document | Scope |\n| --- | --- | --- |\n");
        var n = 0;
        foreach (var section in ordered)
        {
            n++;
            sb.Append("| ").Append(n)
              .Append(" | [").Append(EscapePipes(section.Title)).Append("](").Append(LinkTarget(section.RelativePath)).Append(')')
              .Append(" | ").Append(Cell(section.Scope))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    // Manifest order first (only paths that resolve to a section), then any
    // remaining sections in Ordinal path order. Deterministic either way.
    private static List<FicdSection> OrderedDocuments(FicdProject project)
    {
        var byPath = new Dictionary<string, FicdSection>(StringComparer.Ordinal);
        foreach (var s in project.Sections)
        {
            byPath[s.RelativePath] = s;
        }
        var ordered = new List<FicdSection>();
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var path in project.Manifest.Documents)
        {
            if (byPath.TryGetValue(path, out var s) && used.Add(path))
            {
                ordered.Add(s);
            }
        }
        foreach (var s in project.Sections)
        {
            if (used.Add(s.RelativePath))
            {
                ordered.Add(s);
            }
        }
        return ordered;
    }

    // --- Section ----------------------------------------------------------

    private static string RenderSection(
        FicdSection section, FicdManifest manifest, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        var sb = new StringBuilder();
        AppendIdentity(sb, section.Title, manifest, includeSection: true);
        AppendLead(sb, section.Summary);
        AppendTemplate(sb, section, symbols);
        AppendBody(sb, section.Body);
        AppendRequirements(sb, section.Requirements);
        AppendCrossReferences(sb, section.CrossReferences);
        return Trim(sb);
    }

    private static void AppendIdentity(
        StringBuilder sb, string title, FicdManifest m, bool includeSection)
    {
        sb.Append("# ").Append(title).Append("\n\n");
        sb.Append("| Field | Value |\n| --- | --- |\n");
        AppendRow(sb, "Document Title", m.DocumentTitle);
        AppendRow(sb, "Document Number", m.DocumentNumber);
        if (includeSection)
        {
            AppendRow(sb, "Section", title);
        }
        AppendRow(sb, "Version", m.Version);
        AppendRow(sb, "Date", m.Date);
        AppendRow(sb, "Interface", m.Interface);
        AppendRow(sb, "Package", m.Package);
        AppendRow(sb, "Status", m.Status);
        AppendRow(sb, "Change Authority", m.ChangeAuthority);
        sb.Append('\n');
    }

    private static void AppendRow(StringBuilder sb, string field, string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return;
        }
        sb.Append("| ").Append(field).Append(" | ").Append(Cell(value)).Append(" |\n");
    }

    private static void AppendLead(StringBuilder sb, string summary)
    {
        if (!string.IsNullOrEmpty(summary))
        {
            sb.Append(summary).Append("\n\n");
        }
        sb.Append("---\n\n");
    }

    private static void AppendTemplate(
        StringBuilder sb, FicdSection section, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        switch (section.Template)
        {
            case "services":
                AppendServices(sb, section, symbols);
                break;
            case "functions":
                AppendFunctions(sb, section, symbols);
                break;
            case "data-objects":
                AppendDataObjects(sb, section, symbols);
                break;
            default:
                break;
        }
    }

    // --- services template ------------------------------------------------

    private static void AppendServices(
        StringBuilder sb, FicdSection section, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (section.Inventory)
        {
            AppendServiceInventory(sb, section.Groups);
        }
        var index = 0;
        foreach (var group in section.Groups)
        {
            index++;
            AppendGroupHeading(sb, group, section.Section, index);
            AppendIntro(sb, group.Intro);
            AppendServiceMembers(sb, group, symbols);
        }
    }

    private static void AppendServiceInventory(StringBuilder sb, IReadOnlyList<FicdGroup> groups)
    {
        if (groups.Sum(g => g.Interfaces.Count) == 0)
        {
            return;
        }
        sb.Append("| Capability | Interface | Token | Concrete class | Access |\n");
        sb.Append("| --- | --- | --- | --- | --- |\n");
        foreach (var group in groups)
        {
            for (var i = 0; i < group.Interfaces.Count; i++)
            {
                sb.Append("| ").Append(Cell(group.Title))
                  .Append(" | ").Append(Code(group.Interfaces[i]))
                  .Append(" | ").Append(Code(At(group.Tokens, i)))
                  .Append(" | ").Append(Code(At(group.Classes, i)))
                  .Append(" | ").Append(Cell(group.Access))
                  .Append(" |\n");
            }
        }
        sb.Append('\n');
    }

    private static void AppendServiceMembers(
        StringBuilder sb, FicdGroup group, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        for (var i = 0; i < group.Interfaces.Count; i++)
        {
            var name = group.Interfaces[i];
            var token = At(group.Tokens, i);
            sb.Append("### ").Append(Code(name));
            if (token.Length > 0)
            {
                sb.Append(" / ").Append(Code(token));
            }
            sb.Append("\n\n");
            var concrete = At(group.Classes, i);
            if (concrete.Length > 0)
            {
                sb.Append("Concrete class: ").Append(Code(concrete)).Append(".\n\n");
            }
            AppendMemberTableOrMissing(sb, name, symbols);
        }
    }

    private static void AppendMemberTableOrMissing(
        StringBuilder sb, string name, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (!symbols.TryGetValue(name, out var decl))
        {
            AppendMissing(sb, name);
            return;
        }
        if (!string.IsNullOrEmpty(decl.Doc))
        {
            sb.Append(decl.Doc).Append("\n\n");
        }
        if (decl.Members.Count == 0)
        {
            sb.Append("_No members._\n\n");
            return;
        }
        sb.Append("| Member | Kind | Signature | Description |\n| --- | --- | --- | --- |\n");
        foreach (var m in decl.Members)
        {
            sb.Append("| ").Append(Code(m.Name))
              .Append(" | ").Append(m.MemberKind == "method" ? "Method" : "Property")
              .Append(" | ").Append(Code(MemberSignature(m)))
              .Append(" | ").Append(Cell(m.Doc))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    private static string MemberSignature(ApiMember m)
    {
        if (m.MemberKind == "method")
        {
            var method = m.Optional ? m.Name + "?" : m.Name;
            return $"{method}({ParamList(m.Parameters)}): {ReturnOr(m.ReturnType)}";
        }
        var name = m.Optional ? m.Name + "?" : m.Name;
        var prefix = m.Readonly ? "readonly " : "";
        return $"{prefix}{name}: {NonEmpty(m.Type, "unknown")}";
    }

    // --- functions template -----------------------------------------------

    private static void AppendFunctions(
        StringBuilder sb, FicdSection section, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (section.Inventory)
        {
            AppendFunctionInventory(sb, section.Groups, symbols);
        }
        var index = 0;
        foreach (var group in section.Groups)
        {
            index++;
            AppendGroupHeading(sb, group, section.Section, index);
            AppendIntro(sb, group.Intro);
            AppendFunctionTable(sb, group.Functions, symbols);
        }
    }

    private static void AppendFunctionInventory(
        StringBuilder sb, IReadOnlyList<FicdGroup> groups, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (groups.Sum(g => g.Functions.Count) == 0)
        {
            return;
        }
        sb.Append("| Function | Signature | Description |\n| --- | --- | --- |\n");
        foreach (var group in groups)
        {
            foreach (var fn in group.Functions)
            {
                AppendFunctionInventoryRow(sb, fn, symbols);
            }
        }
        sb.Append('\n');
    }

    private static void AppendFunctionInventoryRow(
        StringBuilder sb, string fn, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (!symbols.TryGetValue(fn, out var d))
        {
            sb.Append("| ").Append(Code(fn)).Append(" | ").Append(MissingCell(fn)).Append(" | – |\n");
            return;
        }
        sb.Append("| ").Append(Code(d.Name))
          .Append(" | ").Append(Code($"{d.Name}({ParamList(d.Parameters)}): {ReturnOr(d.ReturnType)}"))
          .Append(" | ").Append(Cell(d.Doc))
          .Append(" |\n");
    }

    private static void AppendFunctionTable(
        StringBuilder sb, IReadOnlyList<string> functions, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (functions.Count == 0)
        {
            return;
        }
        sb.Append("| Function | Parameters | Returns | Description |\n| --- | --- | --- | --- |\n");
        foreach (var fn in functions)
        {
            AppendFunctionRow(sb, fn, symbols);
        }
        sb.Append('\n');
    }

    private static void AppendFunctionRow(
        StringBuilder sb, string fn, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (!symbols.TryGetValue(fn, out var d))
        {
            sb.Append("| ").Append(Code(fn)).Append(" | ").Append(MissingCell(fn)).Append(" | – | – |\n");
            return;
        }
        sb.Append("| ").Append(Code(d.Name))
          .Append(" | ").Append(Code(ParamsOrNone(d.Parameters)))
          .Append(" | ").Append(Code(ReturnOr(d.ReturnType)))
          .Append(" | ").Append(Cell(d.Doc))
          .Append(" |\n");
    }

    // --- data-objects template --------------------------------------------

    private static void AppendDataObjects(
        StringBuilder sb, FicdSection section, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        var index = 0;
        foreach (var group in section.Groups)
        {
            index++;
            AppendGroupHeading(sb, group, section.Section, index);
            AppendIntro(sb, group.Intro);
            foreach (var name in group.DataObjects)
            {
                AppendDataObject(sb, name, symbols);
            }
            AppendValueSets(sb, group.Types, symbols);
        }
    }

    private static void AppendDataObject(
        StringBuilder sb, string name, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        sb.Append("### ").Append(Code(name)).Append("\n\n");
        if (!symbols.TryGetValue(name, out var d))
        {
            AppendMissing(sb, name);
            return;
        }
        if (!string.IsNullOrEmpty(d.Doc))
        {
            sb.Append(d.Doc).Append("\n\n");
        }
        var properties = d.Members.Where(m => m.MemberKind == "property").ToList();
        AppendFieldsTable(sb, properties);
        AppendInterfaceCode(sb, d.Name, properties);
    }

    private static void AppendFieldsTable(StringBuilder sb, List<ApiMember> properties)
    {
        if (properties.Count == 0)
        {
            sb.Append("_No fields._\n\n");
            return;
        }
        sb.Append("| Field | Type | Required | Description |\n| --- | --- | --- | --- |\n");
        foreach (var p in properties)
        {
            sb.Append("| ").Append(Code(p.Name))
              .Append(" | ").Append(Code(NonEmpty(p.Type, "unknown")))
              .Append(" | ").Append(p.Optional ? "No" : "Yes")
              .Append(" | ").Append(Cell(p.Doc))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    private static void AppendInterfaceCode(StringBuilder sb, string name, List<ApiMember> properties)
    {
        if (properties.Count == 0)
        {
            return;
        }
        sb.Append("```typescript\ninterface ").Append(name).Append(" {\n");
        foreach (var p in properties)
        {
            var prefix = p.Readonly ? "readonly " : "";
            var optional = p.Optional ? "?" : "";
            sb.Append("  ").Append(prefix).Append(p.Name).Append(optional)
              .Append(": ").Append(NonEmpty(p.Type, "unknown")).Append(";\n");
        }
        sb.Append("}\n```\n\n");
    }

    private static void AppendValueSets(
        StringBuilder sb, IReadOnlyList<string> types, IReadOnlyDictionary<string, ApiDeclaration> symbols)
    {
        if (types.Count == 0)
        {
            return;
        }
        sb.Append("| Type | Definition |\n| --- | --- |\n");
        foreach (var t in types)
        {
            sb.Append("| ").Append(Code(t)).Append(" | ");
            if (symbols.TryGetValue(t, out var d))
            {
                sb.Append(Code(d.Definition));
            }
            else
            {
                sb.Append(MissingCell(t));
            }
            sb.Append(" |\n");
        }
        sb.Append('\n');
    }

    // --- shared section parts ---------------------------------------------

    private static void AppendGroupHeading(StringBuilder sb, FicdGroup group, int section, int index)
    {
        var heading = !string.IsNullOrEmpty(group.Heading)
            ? group.Heading
            : (section > 0 ? $"{section}.{index}" : index.ToString());
        sb.Append("## ").Append(heading);
        if (!string.IsNullOrEmpty(group.Title))
        {
            sb.Append(' ').Append(group.Title);
        }
        sb.Append("\n\n");
    }

    private static void AppendIntro(StringBuilder sb, string intro)
    {
        if (!string.IsNullOrEmpty(intro))
        {
            sb.Append(intro).Append("\n\n");
        }
    }

    private static void AppendBody(StringBuilder sb, string body)
    {
        if (!string.IsNullOrEmpty(body))
        {
            sb.Append(body).Append("\n\n");
        }
    }

    private static void AppendRequirements(StringBuilder sb, IReadOnlyList<string> requirements)
    {
        if (requirements.Count == 0)
        {
            return;
        }
        sb.Append("## Requirements\n\n");
        var n = 0;
        foreach (var requirement in requirements)
        {
            n++;
            sb.Append(n).Append(". ").Append(requirement).Append('\n');
        }
        sb.Append('\n');
    }

    private static void AppendCrossReferences(StringBuilder sb, IReadOnlyList<string> references)
    {
        if (references.Count == 0)
        {
            return;
        }
        sb.Append("## Cross-references\n\n");
        foreach (var reference in references)
        {
            sb.Append("- ").Append(reference).Append('\n');
        }
        sb.Append('\n');
    }

    private static void AppendMissing(StringBuilder sb, string name) =>
        sb.Append("_(not found: ").Append(name).Append(")_\n\n");

    // Inline "not found" placeholder that names the missing symbol (table-cell form).
    private static string MissingCell(string name) => "_(not found: " + EscapePipes(name) + ")_";

    // A Markdown link destination. A path with a space or parenthesis is wrapped in
    // angle brackets so the link target is not truncated; plain paths are emitted
    // as-is so the common case stays unchanged.
    private static string LinkTarget(string path) =>
        path.IndexOf(' ') >= 0 || path.IndexOf('(') >= 0 || path.IndexOf(')') >= 0
            ? "<" + path + ">"
            : path;

    // --- formatting helpers (mirrors MarkdownRenderer / InventoryRenderer) -

    private static string ParamList(IReadOnlyList<ApiParameter> parameters) =>
        string.Join(", ", parameters.Select(p =>
            p.Optional ? $"{p.Name}?: {p.Type}" : $"{p.Name}: {p.Type}"));

    private static string ParamsOrNone(IReadOnlyList<ApiParameter> parameters) =>
        parameters.Count == 0 ? "()" : ParamList(parameters);

    private static string ReturnOr(string returnType) => NonEmpty(returnType, "void");

    private static string NonEmpty(string value, string fallback) =>
        string.IsNullOrEmpty(value) ? fallback : value;

    private static string At(IReadOnlyList<string> list, int i) => i < list.Count ? list[i] : "";

    private static string Code(string value) =>
        string.IsNullOrEmpty(value) ? "–" : CodeSpan(EscapePipes(value));

    private static string Cell(string value) =>
        string.IsNullOrEmpty(value) ? "–" : EscapePipes(value);

    private static string EscapePipes(string value) => value.Replace("|", "\\|");

    private static string CodeSpan(string text)
    {
        var fence = new string('`', LongestBacktickRun(text) + 1);
        var pad = text[0] == '`' || text[^1] == '`' ? " " : "";
        return fence + pad + text + pad + fence;
    }

    private static int LongestBacktickRun(string text)
    {
        var longest = 0;
        var current = 0;
        foreach (var c in text)
        {
            current = c == '`' ? current + 1 : 0;
            longest = current > longest ? current : longest;
        }
        return longest;
    }

    private static string Trim(StringBuilder sb) => sb.ToString().TrimEnd('\n') + "\n";
}
