using System.Text;

namespace SurfaceQ.Core;

// Renders a ProjectInventory to Markdown: a title, a Summary (total/exported/
// internal counts plus a per-category count table), then one section per
// non-empty category in a fixed order. Output is deterministic — items are
// sorted by name then file within each category — and table-safe (pipes in
// cell text are escaped). LF endings, single trailing newline.

public sealed class InventoryRenderer
{
    private const string Banner =
        "> Generated by SurfaceQ. Do not edit by hand; regenerate with `surfaceq inventory`.";

    // Category order is the document's reading order. Each entry maps the role
    // the sidecar emits to the plural section title.
    private static readonly (string Role, string Title)[] Categories =
    {
        ("Component", "Components"),
        ("Directive", "Directives"),
        ("Pipe", "Pipes"),
        ("Service", "Services"),
        ("NgModule", "NgModules"),
        ("Guard", "Guards"),
        ("Resolver", "Resolvers"),
        ("Interceptor", "Interceptors"),
        ("Class", "Classes"),
        ("Interface", "Interfaces"),
        ("Enum", "Enums"),
        ("Type Alias", "Type Aliases"),
        ("Function", "Functions"),
        ("Constant", "Constants"),
        ("Injection Token", "Injection Tokens"),
    };

    public string Render(ProjectInventory inventory)
    {
        var sb = new StringBuilder();
        sb.Append("# ").Append(inventory.Name).Append(" — Inventory\n\n");
        sb.Append(Banner).Append("\n\n");
        sb.Append("_Type: ").Append(inventory.Type).Append("_\n\n");

        if (inventory.Items.Count == 0)
        {
            sb.Append("_No developer-authored objects found._\n");
            return sb.ToString();
        }

        var sections = BuildSections(inventory.Items);
        AppendSummary(sb, inventory.Items, sections);
        foreach (var section in sections)
        {
            AppendSection(sb, section);
        }
        // Each section ends with a blank-line separator; drop the final one so
        // the document ends with exactly one trailing newline (L2-034).
        var text = sb.ToString();
        return text.EndsWith("\n\n", StringComparison.Ordinal) ? text[..^1] : text;
    }

    // Groups items into the fixed category order, then any unknown roles into a
    // trailing "Other" section (defensive — the sidecar emits known roles only).
    private static List<Section> BuildSections(IReadOnlyList<InventoryItem> items)
    {
        var sections = new List<Section>();
        var claimed = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (role, title) in Categories)
        {
            var matching = Sorted(items.Where(i => i.Role == role));
            if (matching.Count > 0)
            {
                sections.Add(new Section(title, matching));
                claimed.Add(role);
            }
        }
        var leftover = Sorted(items.Where(i => !claimed.Contains(i.Role)));
        if (leftover.Count > 0)
        {
            sections.Add(new Section("Other", leftover));
        }
        return sections;
    }

    private static List<InventoryItem> Sorted(IEnumerable<InventoryItem> items) =>
        items
            .OrderBy(i => i.Name, StringComparer.Ordinal)
            .ThenBy(i => i.File, StringComparer.Ordinal)
            .ToList();

    private static void AppendSummary(StringBuilder sb, IReadOnlyList<InventoryItem> items, List<Section> sections)
    {
        var exported = items.Count(i => i.Exported);
        var internalCount = items.Count - exported;
        sb.Append("## Summary\n\n");
        sb.Append(Count(items.Count, "object"))
          .Append(" (").Append(exported).Append(" exported, ")
          .Append(internalCount).Append(" internal).\n\n");
        sb.Append("| Category | Count |\n");
        sb.Append("| --- | --- |\n");
        foreach (var section in sections)
        {
            sb.Append("| ").Append(section.Title).Append(" | ").Append(section.Items.Count).Append(" |\n");
        }
        sb.Append('\n');
    }

    private static void AppendSection(StringBuilder sb, Section section)
    {
        sb.Append("## ").Append(section.Title).Append("\n\n");
        sb.Append("| Name | Kind | Exported | File | Description |\n");
        sb.Append("| --- | --- | --- | --- | --- |\n");
        foreach (var item in section.Items)
        {
            sb.Append("| ").Append(Code(item.Name))
              .Append(" | ").Append(Code(item.Kind))
              .Append(" | ").Append(item.Exported ? "yes" : "no")
              .Append(" | ").Append(Code(item.File))
              .Append(" | ").Append(Cell(item.Doc))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    private static string Count(int n, string noun) =>
        n == 1 ? $"1 {noun}" : $"{n} {noun}s";

    private static string Code(string value) =>
        string.IsNullOrEmpty(value) ? "–" : CodeSpan(EscapePipes(value));

    private static string Cell(string value) =>
        string.IsNullOrEmpty(value) ? "–" : EscapePipes(value);

    private static string EscapePipes(string value) => value.Replace("|", "\\|");

    // Wraps text in a Markdown code span whose backtick fence is one longer than
    // the longest backtick run inside, padding with a space when the text begins
    // or ends with a backtick. A value such as a template-literal type
    // (`a-${string}`) therefore cannot close the span early and spill the row.
    private static string CodeSpan(string text)
    {
        var fence = new string('`', LongestBacktickRun(text) + 1);
        var pad = text[0] == '`' || text[^1] == '`' ? " " : "";
        return fence + pad + text + pad + fence;
    }

    private static int LongestBacktickRun(string text)
    {
        var longest = 0;
        var current = 0;
        foreach (var c in text)
        {
            current = c == '`' ? current + 1 : 0;
            longest = current > longest ? current : longest;
        }
        return longest;
    }

    private sealed record Section(string Title, IReadOnlyList<InventoryItem> Items);
}
