using System.Text;

namespace SurfaceQ.Core;

// Generates an Angular `provide-<project>.ts` from a library's extracted API.
// For every `InjectionToken<T>`:
//   - if T is an interface implemented by an exported class, the token is bound
//     to that class with `useExisting`;
//   - otherwise T is treated as a configuration value and bound with `useValue`
//     from a generated `Provide<Project>Options` field.
// The file is placed at the common-ancestor directory of the wired declarations
// (so relative imports match the existing source layout) and is deterministic:
// tokens are ordered by name, imports grouped per module and sorted. Content is
// joined with explicit "\n" for LF regardless of how this source is checked out.
// Mirrors the hand-written shape of provide-api.ts. A future revision will honor
// @internal / @publicApi JSDoc tags; v1 includes every implemented contract.

public sealed class ProviderGenerator
{
    public GeneratedProvider Generate(LibraryApi api, string projectName)
    {
        var (config, services, warnings) = Classify(api);
        var functionName = "provide" + Pascal(projectName);
        if (config.Count == 0 && services.Count == 0)
        {
            return new GeneratedProvider(functionName, "", "", 0, warnings);
        }
        var imports = BuildImports(api, config, services);
        var anchorDir = CommonAncestor(imports.Select(i => i.File).ToList());
        var targetFile = Path.Combine(anchorDir, "provide-" + Slug(projectName) + ".ts");
        var content = Render(functionName, projectName, config, services, imports, anchorDir);
        return new GeneratedProvider(functionName, targetFile, content, config.Count + services.Count, warnings);
    }

    private static (List<ConfigToken> Config, List<ServiceBinding> Services, List<string> Warnings) Classify(
        LibraryApi api)
    {
        var interfaces = new HashSet<string>(
            api.Declarations.Where(d => d.Kind == "interface").Select(d => d.Name), StringComparer.Ordinal);
        var classes = api.Declarations.Where(d => d.Kind == "class").ToList();
        var config = new List<ConfigToken>();
        var services = new List<ServiceBinding>();
        var warnings = new List<string>();

        var tokens = api.Declarations
            .Where(d => d.Kind == "injection-token")
            .OrderBy(d => d.Name, StringComparer.Ordinal);
        foreach (var token in tokens)
        {
            var contract = BaseName(token.Contract);
            if (!interfaces.Contains(contract))
            {
                var type = string.IsNullOrEmpty(token.Contract) ? "unknown" : token.Contract;
                config.Add(new ConfigToken(token, CamelFromToken(token.Name), type));
                continue;
            }
            var impl = classes
                .Where(c => c.Implements.Select(BaseName).Contains(contract))
                .OrderBy(c => c.Name, StringComparer.Ordinal)
                .FirstOrDefault();
            if (impl != null)
            {
                services.Add(new ServiceBinding(token, impl));
            }
            else
            {
                warnings.Add($"token {token.Name}: interface {contract} has no implementation; skipped");
            }
        }
        return (config, services, warnings);
    }

    // Symbol-name/declaring-file pairs to import: each token and impl class, plus
    // any config-token value type that resolves to an exported declaration.
    private static List<Import> BuildImports(
        LibraryApi api, List<ConfigToken> config, List<ServiceBinding> services)
    {
        var byName = new Dictionary<string, ApiDeclaration>(StringComparer.Ordinal);
        foreach (var d in api.Declarations)
        {
            if (!byName.ContainsKey(d.Name))
            {
                byName[d.Name] = d;
            }
        }
        var imports = new List<Import>();
        foreach (var c in config)
        {
            imports.Add(new Import(c.Token.Name, c.Token.File));
            if (byName.TryGetValue(BaseName(c.Type), out var typeDecl))
            {
                imports.Add(new Import(typeDecl.Name, typeDecl.File));
            }
        }
        foreach (var s in services)
        {
            imports.Add(new Import(s.Token.Name, s.Token.File));
            imports.Add(new Import(s.Impl.Name, s.Impl.File));
        }
        return imports.Where(i => !string.IsNullOrEmpty(i.File)).ToList();
    }

    private static string Render(
        string functionName,
        string projectName,
        List<ConfigToken> config,
        List<ServiceBinding> services,
        List<Import> imports,
        string anchorDir)
    {
        var sb = new StringBuilder();
        sb.Append("// This file is generated by SurfaceQ. Do not edit by hand.\n");
        sb.Append("// Regenerate with: surfaceq providers\n\n");
        AppendImports(sb, imports, anchorDir);
        var optionsType = "Provide" + Pascal(projectName) + "Options";
        if (config.Count > 0)
        {
            AppendOptions(sb, optionsType, config);
        }
        sb.Append("export function ").Append(functionName).Append('(');
        if (config.Count > 0)
        {
            sb.Append("options: ").Append(optionsType);
        }
        sb.Append("): EnvironmentProviders {\n");
        sb.Append("  return makeEnvironmentProviders([\n");
        foreach (var c in config)
        {
            sb.Append("    { provide: ").Append(c.Token.Name)
              .Append(", useValue: options.").Append(c.Field).Append(" },\n");
        }
        foreach (var s in services)
        {
            sb.Append("    { provide: ").Append(s.Token.Name)
              .Append(", useExisting: ").Append(s.Impl.Name).Append(" },\n");
        }
        sb.Append("  ]);\n}\n");
        return sb.ToString();
    }

    private static void AppendImports(StringBuilder sb, List<Import> imports, string anchorDir)
    {
        sb.Append("import { EnvironmentProviders, makeEnvironmentProviders } from '@angular/core';\n");
        var byModule = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        foreach (var import in imports)
        {
            var module = ModuleSpecifier(anchorDir, import.File);
            if (!byModule.TryGetValue(module, out var names))
            {
                names = new SortedSet<string>(StringComparer.Ordinal);
                byModule[module] = names;
            }
            names.Add(import.Name);
        }
        foreach (var module in byModule.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            sb.Append("import { ").Append(string.Join(", ", byModule[module]))
              .Append(" } from '").Append(module).Append("';\n");
        }
        sb.Append('\n');
    }

    private static void AppendOptions(StringBuilder sb, string optionsType, List<ConfigToken> config)
    {
        sb.Append("export interface ").Append(optionsType).Append(" {\n");
        foreach (var c in config)
        {
            sb.Append("  readonly ").Append(c.Field).Append(": ").Append(c.Type).Append(";\n");
        }
        sb.Append("}\n\n");
    }

    private static string ModuleSpecifier(string anchorDir, string file)
    {
        var relative = Path.GetRelativePath(anchorDir, Path.GetFullPath(file)).Replace('\\', '/');
        if (relative.EndsWith(".ts", StringComparison.Ordinal))
        {
            relative = relative[..^3];
        }
        return relative.StartsWith(".", StringComparison.Ordinal) ? relative : "./" + relative;
    }

    // The longest shared directory prefix of the given files; the single file's
    // directory when there is one. Compared case-insensitively for Windows.
    private static string CommonAncestor(IReadOnlyList<string> files)
    {
        var dirs = files
            .Select(f => Path.GetDirectoryName(Path.GetFullPath(f))!)
            .Distinct()
            .ToList();
        if (dirs.Count == 1)
        {
            return dirs[0];
        }
        var split = dirs
            .Select(d => d.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))
            .ToList();
        var common = new List<string>();
        var limit = split.Min(s => s.Length);
        for (var i = 0; i < limit; i++)
        {
            var segment = split[0][i];
            if (split.All(s => string.Equals(s[i], segment, StringComparison.OrdinalIgnoreCase)))
            {
                common.Add(segment);
            }
            else
            {
                break;
            }
        }
        return string.Join(Path.DirectorySeparatorChar.ToString(), common);
    }

    // "ns.IFoo<Bar>" -> "IFoo": drop type arguments, then any namespace qualifier.
    private static string BaseName(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return "";
        }
        var name = text.Trim();
        var generic = name.IndexOf('<');
        if (generic >= 0)
        {
            name = name[..generic];
        }
        var dot = name.LastIndexOf('.');
        if (dot >= 0)
        {
            name = name[(dot + 1)..];
        }
        return name.Trim();
    }

    private static string Pascal(string name)
    {
        var sb = new StringBuilder();
        foreach (var word in SplitWords(name))
        {
            var lower = word.ToLowerInvariant();
            sb.Append(char.ToUpperInvariant(lower[0])).Append(lower[1..]);
        }
        return sb.Length > 0 ? sb.ToString() : "Library";
    }

    private static string Slug(string name)
    {
        var slug = string.Join("-", SplitWords(name).Select(w => w.ToLowerInvariant()));
        return slug.Length > 0 ? slug : "library";
    }

    // "API_BASE_URL" -> "apiBaseUrl".
    private static string CamelFromToken(string token)
    {
        var words = SplitWords(token);
        if (words.Count == 0)
        {
            return "value";
        }
        var sb = new StringBuilder(words[0].ToLowerInvariant());
        for (var i = 1; i < words.Count; i++)
        {
            var lower = words[i].ToLowerInvariant();
            sb.Append(char.ToUpperInvariant(lower[0])).Append(lower[1..]);
        }
        return sb.ToString();
    }

    private static List<string> SplitWords(string text)
    {
        var words = new List<string>();
        var sb = new StringBuilder();
        foreach (var c in text)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (sb.Length > 0)
            {
                words.Add(sb.ToString());
                sb.Clear();
            }
        }
        if (sb.Length > 0)
        {
            words.Add(sb.ToString());
        }
        return words;
    }

    private sealed record ConfigToken(ApiDeclaration Token, string Field, string Type);

    private sealed record ServiceBinding(ApiDeclaration Token, ApiDeclaration Impl);

    private sealed record Import(string Name, string File);
}
